theme: jekyll-theme-minimal
title: Security and Microservices
description: Get started with security for your cloud native Java Microservices application
show_downloads: True
navigation:
  - title: Overview
    url: /
  - title: 1 - Setup the work environment
    url: workshop/01-pre-work/prework
  - title: 2 - Setup Istio
    url: workshop/02-app-env-exercise/SETUP_ISTIO
  - title: 3 - Istio Ingress gateway via HTTPS/TLS
    url: workshop/02-app-env-exercise/SETUP_ISTIO_INGRESS
  - title: 4 - Setup Keycloak
    url: workshop/02-app-env-exercise/SETUP_KEYCLOAK
  - title: 5 - Deploy the microservices to Kubernetes
    url: workshop/03-p-sec-exercise/01-README
  - title: 6 - Strict mTLS
    url: workshop/03-p-sec-exercise/02-README
  - title: 7 - Istio Authorization
    url: workshop/03-p-sec-exercise/03-README
  - title: 8 - Authentication in the Vue.js fronted
    url: workshop/04-app-sec-exercise/APPLICATION_AUTHENTICATION
  - title: 9 - Authorization in Quarkus app
    url: workshop/04-app-sec-exercise/APPLICATION_AUTHORIZATION
  - title: Setup locally
    url: workshop/04-app-sec-exercise/local

