theme: jekyll-theme-minimal
title: Security and Microservices
description: Get started with security for your Java Microservices application
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Prework
  - title: Setup the Kubernetes environment
    url: workshop/01-pre-work/prework
