theme: jekyll-theme-minimal
title: Security and Microservices
description: Get started with security for your Java Microservices application
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Pre-Work
    url: workshop/prework
